//
//  CarCatalog.swift
//  vr
//
//  What a car is, and the list of the ones that ship.
//

import Foundation

/// One playable car.
///
/// Instances are generated by `Tools/build_cars.py` into
/// `CarCatalogGenerated.swift`: geometry, paint colour and orientation are
/// measured from the model itself so they cannot drift out of step with it.
struct CarDefinition: Identifiable, Hashable {

    /// How this car's colour can be changed, if at all.
    enum PaintSource: Hashable {
        /// The paint is a region of a base-colour map, which gets rewritten.
        case texture(name: String, fileExtension: String)
        /// The paint is a flat material colour, which gets re-tinted.
        case materialColour
        /// No identifiable paint — usually a grey or white model whose only
        /// saturated pixels are its lights. It keeps the colours it shipped with.
        case fixed
    }

    let id: String
    let displayName: String
    let tagline: String
    /// Base name of the `.usdz` in the bundle.
    let assetName: String
    let carClass: CarClass
    /// Real-world length of the placed car, in metres.
    let length: Float

    let paintSource: PaintSource
    /// Hue of the car's paint in its source, in degrees, and how far either
    /// side still counts as paint. Everything outside that window — glass,
    /// tyres, lights, trim — is left alone when the car is repainted.
    let paintHue: Float
    let paintHueTolerance: Float
    let paintSaturation: Float
    let paintBrightness: Float

    var isRepaintable: Bool {
        if case .fixed = paintSource { return false }
        return true
    }

    /// The loose base-colour map, when repainting works by rewriting one.
    var paintTexture: (name: String, fileExtension: String)? {
        if case .texture(let name, let ext) = paintSource { return (name, ext) }
        return nil
    }

    // MARK: - Stat bars

    /// 0...1 values for the garage read-out, taken from the same class
    /// reference the physics is built from, so the bars can never disagree
    /// with how the car actually drives.
    var stats: [(name: String, value: Float)] {
        let reference = carClass.reference
        return [
            ("Speed", normalise(reference.topSpeed, 1.3, 2.5)),
            ("Power", normalise(reference.acceleration, 1.5, 3.7)),
            ("Grip", normalise((reference.frontGrip + reference.rearGrip) / 2, 0.6, 1.22)),
            ("Agility", normalise(reference.steer, 19, 35)),
        ]
    }

    /// How eagerly this car steps its rear out, 0...1. Shown in the garage so
    /// the drift-happy cars are findable.
    var slideTendency: Float {
        let reference = carClass.reference
        return normalise(reference.frontGrip / max(reference.rearGrip, 0.01), 1.0, 1.6)
    }

    private func normalise(_ value: Float, _ low: Float, _ high: Float) -> Float {
        min(max((value - low) / (high - low), 0.08), 1)
    }
}

enum CarCatalog {

    static var all: [CarDefinition] { generated }

    static func car(id: String) -> CarDefinition {
        all.first { $0.id == id } ?? all[0]
    }

}
